# Generated by Django 5.0.4 on 2024-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_product', '0002_product_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.CharField(blank=True, default='0.00', max_length=255, null=True),
        ),
    ]
