# Generated by Django 5.0.4 on 2024-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_product', '0004_productuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
